name: hst_project
description: "HST POS Clone Project"

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.6

  #Core
  flutter_riverpod: ^2.5.1
  animated_text_kit: ^4.2.2
  get: ^4.6.6
  shared_preferences: ^2.2.3
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0 

  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/icon/
    - assets/image/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700